# Param from manifest
PACKAGE_NAME = "PACKAGE_NAME"
CI_TEST_RECORD_ID = "CI_TEST_RECORD_ID"
MONKEY_ROUND = "MONKEY_ROUND"
MONKEY_ROUND_MAXIMUM_TIME = "MONKEY_ROUND_MAXIMUM_TIME"
MONKEY_SEED = "MONKEY_SEED"
MONKEY_PARAM = "MONKEY_PARAM"
TARGET_LANGUAGE = "TARGET_LANGUAGE"
TARGET_REGION = "TARGET_REGION"
TESTER = "TESTER"
ISSUE_WATCHERS = "ISSUE_WATCHERS"

# mongo debug
MONGO_DEBUG = False
APK_BUILD_ID_NEW_CI_PREFIX = "CI_"
