# Test case name
COMMON_PRESETTING = "CommonPreSetting"
GAME_CENTER_PRESETTING = "GameCenterPreSetting"
MUSIC_PRESETTING = "MusicPreSetting"
REMOVE_ACCOUNT = "com.mi.globalAutoTestTool.sanityCheck.V10.specialRegionCases.Test_Z0000001_END"
BROWSER_PRESETTING = "BrowserPreSetting"
GLOBAL_FILE_EXPLORER_PRESETTING = "GlobalFileExplorerPreSetting"
MI_DROP_PRESETTING = "MiDropPreSetting"
PANI_PURI_PRESETTING = "PanipuriPreSetting"
POCO_LAUNCHER_PRESETTING = "PocoLauncherPreSetting"
MINT_BROWSER_PRESETTING = "MintBrowserPreSetting"
DOWNLOAD_PRESETTING = "DownloadPreSetting"
